local C = {
  SET_TIMER_TO_999_PER_EPISODE=false, TESTING_INFINITE_LIVES=false,
  USE_FIXED_TRAINING_STATE=true, TRAINING_SAVESTATE_SLOT=9,
  LEVEL_START_MAX_X=128, PLAY_CHAMPION_ONLY=false,
  SENSOR_RADIUS_TILES=6, GRID_WIDTH=13, GRID_INPUT_COUNT=169,
  GLOBAL_INPUT_COUNT=15, OBSERVATION_INPUT_COUNT=184, NEURAL_INPUT_COUNT=185,
  ACTION_COUNT=6, DURATION_OUTPUT_COUNT=4, NETWORK_OUTPUT_COUNT=10,
  OUTPUT_NODE_OFFSET=1000000, MEMORY_INPUT_OFFSET=900000,
  MEMORY_FEATURE_COUNT=15, MEMORY_LAGS={1,4}, MEMORY_INPUT_COUNT=30,
  ACTION_HOLD_FRAMES={1,2,4,6}, NOVELTY_ARCHIVE_LIMIT=48,
  EPISODE_HISTORY_LIMIT=1000, TOP_PERFORMER_LIMIT=5,
  EXPERIENCE_CONTEXT_LIMIT=512, EXPERIENCE_TRACE_LIMIT=64,
  DEFAULT_POPULATION_SIZE=300, SPECIES_DISTANCE_THRESHOLD=1.0,
  MAX_STALE_GENERATIONS=15, SAVE_INTERVAL_FRAMES=600,
  INITIAL_PROGRESS_DEADLINE_FRAMES=180, MIN_INITIAL_PROGRESS_PIXELS=16,
  ACTION_OPTIONS={
    {name="run",right=true,B=true},
    {name="jump_run",right=true,B=true,A=true},
    {name="retreat",left=true,B=true},
    {name="brake"},
    {name="jump_place",A=true},
    {name="walk",right=true},
  },
  NON_STOMPABLE_ENEMIES={[0x07]=true,[0x0C]=true,[0x0D]=true,[0x11]=true,[0x12]=true},
}
C.clamp=function(value,low,high) return math.max(low,math.min(high,value)) end
return C
